### PR TITLE
Initial Electron Support

### PR DESCRIPTION
**Pull request by dixonwille**
The Idea is to start your application as an API when electron runs. Using the the docs here:
https://nodejs.org/docs/latest-v5.x/api/child_process.html#child_process_child_process_spawn_command_args_options
 
But I don't know they layout you want or if you want your package to always write to file?

### CODE REVIEW

**Comment by dixonwille** [comment]
This is regarding #10

**Comment by dixonwille** [comment]
More reading is required to figure out the actual way to distribute the package http://electron.atom.io/docs/tutorial/application-distribution/

**Comment by ArxdSilva** [comment]
I'll read the refs and soon we'll talk more about this, thanks @dixonwille

**Comment by dixonwille** [comment]
👍 just let me know my email is on my profile if you need more help

**Pull request merged**
